// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback:                       1
// Total number of exported functions:  10

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    yatb_proxy
    (
        init => init
        get_allowed_executor => get_allowed_executor
        add_allowed_lp => add_allowed_lp
        remove_allowed_lp => remove_allowed_lp
        is_allowed_lp => is_allowed_lp
        deposit => deposit
        withdraw => withdraw
        swap => swap
        upgrade => upgrade
    )
}

multiversx_sc_wasm_adapter::async_callback! { yatb_proxy }
